# Binary Prediction of Smoker Status Using Bio Signals

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pytplot as plt
import seaborn as sns
import warnings 

warnings.filterwarnings('ignore')

In [2]:
train = pd.read_csv(r'D:/Data Science Project/1.2.3 Challenge/Binary-Prediction-of-Smoker-Status-Using-Bio-Signals/Data/train.csv')

In [3]:
train.head()

,id,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,...,HDL,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,dental caries,smoking
0,0,55,165,60,81.0,0.5,0.6,1,1,135,...,40,75,16.5,1,1.0,22,25,27,0,1
1,1,70,165,65,89.0,0.6,0.7,2,2,146,...,57,126,16.2,1,1.1,27,23,37,1,0
2,2,20,170,75,81.0,0.4,0.5,1,1,118,...,45,93,17.4,1,0.8,27,31,53,0,1
3,3,35,180,95,105.0,1.5,1.2,1,1,131,...,38,102,15.9,1,1.0,20,27,30,1,0
4,4,30,165,60,80.5,1.5,1.0,1,1,121,...,44,93,15.4,1,0.8,19,13,17,0,1

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159256 entries, 0 to 159255
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   159256 non-null  int64
 1   age                  159256 non-null  int64
 2   height(cm)           159256 non-null  int64
 3   weight(kg)           159256 non-null  int64
 4   waist(cm)            159256 non-null  float64
 5   eyesight(left)       159256 non-null  float64
 6   eyesight(right)      159256 non-null  float64
 7   hearing(left)        159256 non-null  int64
 8   hearing(right)       159256 non-null  int64
 9   systolic             159256 non-null  int64
 10  relaxation           159256 non-null  int64
 11  fasting blood sugar  159256 non-null  int64
 12  Cholesterol          159256 non-null  int64
 13  triglyceride         159256 non-null  int64
 14  HDL                  159256 non-null  int64
 15  LDL                  159256 non-null  int64
 16  hemoglobin           159256 non-null  float64
 17  Urine protein        159256 non-null  int64
 18  serum creatinine     159256 non-null  float64
 19  AST                  159256 non-null  int64
 20  ALT                  159256 non-null  int64
 21  Gtp                  159256 non-null  int64
 22  dental caries        159256 non-null  int64
 23  smoking              159256 non-null  int64
dtypes: float64(5), int64(19)
memory usage: 29.2 MB

In [5]:
train.describe().T

,count,mean,std,min,25%,50%,75%,max
id,159256.0,79627.500000,45973.391572,0.0,39813.75,79627.5,119441.25,159255.0
age,159256.0,44.306626,11.842286,20.0,40.00,40.0,55.00,85.0
height(cm),159256.0,165.266929,8.818970,135.0,160.00,165.0,170.00,190.0
weight(kg),159256.0,67.143662,12.586198,30.0,60.00,65.0,75.00,130.0
waist(cm),159256.0,83.001990,8.957937,51.0,77.00,83.0,89.00,127.0
eyesight(left),159256.0,1.005798,0.402113,0.1,0.80,1.0,1.20,9.9
eyesight(right),159256.0,1.000989,0.392299,0.1,0.80,1.0,1.20,9.9
hearing(left),159256.0,1.023974,0.152969,1.0,1.00,1.0,1.00,2.0
hearing(right),159256.0,1.023421,0.151238,1.0,1.00,1.0,1.00,2.0
systolic,159256.0,122.503648,12.729315,77.0,114.00,121.0,130.00,213.0
relaxation,159256.0,76.874071,8.994642,44.0,70.00,78.0,82.00,133.0
fasting blood sugar,159256.0,98.352552,15.329740,46.0,90.00,96.0,103.00,375.0
Cholesterol,159256.0,195.796165,28.396959,77.0,175.00,196.0,217.00,393.0
triglyceride,159256.0,127.616046,66.188989,8.0,77.00,115.0,165.00,766.0
HDL,159256.0,55.852684,13.964141,9.0,45.00,54.0,64.00,136.0
LDL,159256.0,114.607682,28.158931,1.0,95.00,114.0,133.00,1860.0
hemoglobin,159256.0,14.796965,1.431213,4.9,13.80,15.0,15.80,21.0
Urine protein,159256.0,1.074233,0.347856,1.0,1.00,1.0,1.00,6.0
serum creatinine,159256.0,0.892764,0.179346,0.1,0.80,0.9,1.00,9.9
AST,159256.0,25.516853,9.464882,6.0,20.00,24.0,29.00,778.0
ALT,159256.0,26.550296,17.753070,1.0,16.00,22.0,32.00,2914.0
Gtp,159256.0,36.216004,31.204643,2.0,18.00,27.0,44.00,999.0
dental caries,159256.0,0.197996,0.398490,0.0,0.00,0.0,0.00,1.0
smoking,159256.0,0.437365,0.496063,0.0,0.00,0.0,1.00,1.0